basePath: /
host: localhost:8080
info:
  contact:
    email: jefriherditriyanto@gmail.com
    name: Jefri Herdi Triyanto
  description: lagi belajar asik golang sampe mampus :v
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GO Fiber Training
  version: "1.0"
paths: {}
swagger: "2.0"
